[package]
name = "grim"
version = "0.0.0"
edition = "2021"

[profile.release]
strip = true

[dependencies]
ariadne = "0.3"
bytemuck = "1.13"
clap = { version = "4.4", features = ["derive"] }
nvm = { path = "../nvm" }
unicode-ident = "1.0"
